sudo: required

services:
- docker

language: scala

scala:
- 2.12.7

env:
  global:
  - DOCKER_REPO: nielsdenissen/airlock
  - secure: OCSEVmSvzvmUlkfng4Ie1ZRRdOxtxA5bEL1XQRlcPyQ5BmKxv00WtF8pPUEciRDOtJfSi3XAsnpi0OBi9k1tcSLZ7Z56OKG/BWWERx7yYw88fNHpsBeIDFfKQXAWh6u0U0nzrtdkA7dnnkjWXITz//Tj3fDagIBmoOPIRv6qbpHZ+sz5ygMop30Vl51hrcz1ut12lTK8iR9yZ2o+E7xnV7ALCPkzPcFepRvm6Lv9X1xMSO2D1h6K0iIdgQ9O1SaawdX9e23nAr1pDEKAoF9abslvzVdma1jUmY2fdJVD2LCD/EGkVX5dxYwno+ITFNrDANcY/zVqA9AT3zHkiNUCADDKU0dhPCgNw+yYfYkR8vRlDG3hZVoLb6CqfRKDB+Oi4r57Ne1CWMuyJ9rtxUhQteaSrEZk+zwsGDQNaSZ2zF0WiijfUvKZqVFQ2fDVjVEa81cPqbYk36Jy4r2X4A4K9GT2umHSZNBE5Gx9Ku0l8vBRlKYAqufH+2SUtJsS7Ifq4HTVbQK9kdrShui/GXX1lbLThk9T7f9HUGCfHV5hyUQ8+DOrN322Pdu+VCpudLbZ/R78LPOVbvdtaIcrqghTEzvR3Rs92XiPD+sHMdzXn5r6IKzd2qEdJp7dogRU+vZiz6dzzXq4fymszRnoGt3XhQ0nr/R5EWqvyYLZAVmvQDk=
  - secure: eWBEUWG/L4HzFuzJgJs50AFFhF7NLs0u+G6DRU9QSwxQdyzN22LALEFvxB+WRiZ+aLjOp7/gHJooVYSaXIrE3QJJuG9fd+pv0iSzkwMEAQT74R2THowpm+y0DKLDNiaRKXWwyZWQIVA668BO5syGe8oz00oQ92F0WS/gurD2EeMXWmvbvhdA32HXtrA4DqEtOy6D6dLEhT46hgkC7D1g8Y5IgIGjQF3zdTwpOSjwy9CK48Fq5vQjWD10Mrw5rEylBAxJpK0yCkLDjiap8CCpzsxYiIrThBAWpxDNEDkQ+RA3+fYyvMuqpCzmLY8I69GMdFhIRz8oUbEUSV5+dMy3CNfSDOHg3xz5LtKKKHvWTxQajshLzZgqr1itmz80F0fuSKswLFskHbD1ycxcvxfuedMhwTLkbGX8JXcp2T6xvvjOTFUT4adugmm4AR18UZ1Rdqior47+1VSvI6d3RiSnJWEDcKnzBv8vWnmD0EZKDaDu+6TkDJ7ZuQqkz834qYEiZbkuUDVzfGVzxAf0uJ9rOIC0uoeehzMy3KTYGJhxoKTAy2uLTL6wNSyFtuyRpeSIn3ZYbxvN4P9YjjvtaYNRsNSmA+ym8cdTgx/i0LouU75lMZpquKXAxav9ZqhIjrsi4sozIi6mdemeNTF9bzFCFgdw26jCi8KAYVNIClnbxD0=

before_script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- echo "Starting dependent containers for testing"
- docker-compose up -d
- echo "Compile the project while containers are starting up"
- sbt ++$TRAVIS_SCALA_VERSION clean compile
- echo "Wait for containers to be up and running"
- bash waitForContainerSetup.sh
- docker-compose exec ceph radosgw-admin user modify --uid ceph-admin --system
- docker-compose exec ceph s3cmd put /etc/issue s3://demobucket/subdir/
- docker-compose exec ceph s3cmd mb s3://home
- docker-compose exec ceph s3cmd put /etc/issue s3://home/testuser/
- docker-compose exec ceph s3cmd put /etc/issue s3://home/testuser1/

script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)
- export DOCKER_TAG="${TRAVIS_BRANCH/\//_}"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- if [ "${TRAVIS_BRANCH}" != "master" ]; then
    echo "Build image for with name $DOCKER_REPO:$DOCKER_TAG";
    sbt clean docker:publish;
  fi
- if [ -n "$TRAVIS_TAG" ]; then
    docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:latest;
    docker push $DOCKER_REPO:latest;
  fi

after_script:
- docker-compose down
