version: "3"
services:

  ceph:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    environment:
      - CEPH_DEMO_UID=ceph-admin
      - CEPH_DEMO_ACCESS_KEY=accesskey
      - CEPH_DEMO_SECRET_KEY=secretkey
      - CEPH_DEMO_BUCKET=demobucket
      - RGW_NAME=localhost
      - RGW_CIVETWEB_PORT=8010
      - NETWORK_AUTO_DETECT=4
      - RESTAPI_LOG_LEVEL=debug
    ports:
      - 8010:8010
      - 5000:5000
    command: demo

  postgres-server:
    image: wbaa/airlock-dev-apache-ranger-postgres:0.0.13

  ranger-admin:
    image: wbaa/airlock-dev-apache-ranger:0.0.16
    stdin_open: true
    tty: true
    depends_on:
    - "postgres-server"
    - "ceph"
    ports:
    - "6080:6080"

  airlock-sts:
    image: wbaa/airlock-sts:0.1.9
    environment:
    - STS_HOST=0.0.0.0
    - STS_PORT=12345
    - KEYCLOAK_PUBLIC_KEY_ID=FJ86GcF3jTbNLOco4NvZkUCIUmfYCqoqtOQeMfbhNlE
    - KEYCLOAK_URL=http://keycloak:8080
    - KEYCLOAK_CHECK_REALM_URL=false
    - KEYCLOAK_CHECK_ISSUER_FOR_LIST=sts-airlock
    - MARIADB_URL=jdbc:mysql:loadbalance://mariadb:3306,mariadb:3306/airlock
    ports:
    - "12345:12345"
    depends_on:
    - "keycloak"
    - "mariadb"

  keycloak:
    image: wbaa/airlock-dev-keycloak:0.0.4
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    ports:
    - "8080:8080"

  atlas:
    image: wbaa/airlock-dev-apache-atlas:0.0.5
    ports:
    - "21000:21000"

  mariadb:
    image: wbaa/airlock-dev-mariadb:0.0.2
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    ports:
    - 3307:3306
