version: "2"
services:
  ceph:
    image: ceph/daemon:latest-mimic
    environment:
      - CEPH_DEMO_UID=ceph-admin
      - CEPH_DEMO_ACCESS_KEY=accesskey
      - CEPH_DEMO_SECRET_KEY=secretkey
      - CEPH_DEMO_BUCKET=demobucket
      - RGW_NAME=localhost
      - RGW_CIVETWEB_PORT=8010
      - NETWORK_AUTO_DETECT=4
      - RESTAPI_LOG_LEVEL=debug
    ports:
      - 8010:8010
      - 5000:5000
    command: demo
  postgres-server:
    image: nielsdenissen/ranger-postgres
    ports:
      - "5432:5432"
  ranger-admin:
    image: nielsdenissen/ranger-admin
    stdin_open: true
    tty: true
    depends_on:
      - "postgres-server"
    ports:
      - "6080:6080"
